CREATE DATABASE IF NOT EXISTS streaming;
USE streaming;

CREATE TABLE IF NOT EXISTS users (
  user_ID INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(255),
  email VARCHAR(255),
  password VARCHAR(255)
);

 CREATE TABLE IF NOT EXISTS movies (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255),
  year INTEGER,
  genre VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS views (
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users (id),
  movie_id INTEGER NOT NULL REFERENCES movies (id),
  date DATETIME
);